-- INNER JOIN :- The most used join in the sql and the most common question to be asked in the interview.
-- So this inner join will just match the records from both the tables or common record between the table as per joining the key.



-- creating a new database for the joins_practice

create database joins_practice;
use joins_practice;

-- Not adding any foreign key.
-- creating tables:customer,orders,product,payment.

-- DDL FOR THE CUSTOMER TABLE
create table if not exists customer
(
customer_id int primary key,
customer_name varchar(50),
city varchar(50),
signup_date date
);

-- DDL FOR THE ORDERS TABLE.
create table if not exists orders
(
order_id int primary key,
customer_id int,
product_id int,
order_amount decimal(10,2),
order_date date,
order_status varchar(50)
);

-- DDL FOR THE PRODUCT TABLE
create table if not exists product
(
product_id int primary key,
product_name varchar(50) not null,
category varchar(50)
);

-- DDL FOR THE PAYEMENT TABLE.
create table if not exists payement
(
payment_id int primary key,
order_id int,
payment_mode varchar(50),
payment_status varchar(50),
paid_amount decimal(10,2),
payment_date date
);

-- inserting samples in the table.(Customer)
INSERT INTO customer(customer_id,customer_name,city,signup_date)
VALUES
(1,'Sagar','Kathmandu','2026-06-29'),
(2,'Aayush','Pokhara','2026-06-27'),
(3,'Prabin','Lalitpur','2025-03-22'),
(4,'Shristi','Bhaktapur','2026-05-29'),
(5,'Roshan','Biratnagar','2026-06-30'),
(6,'Samiksha','Butwal','2026-05-31'),
(7,'Anish','Chitwan','2026-03-15'),
(8,'Sushmita','Dharan','2026-02-06');

-- Inserting samples in the table.(Orders)
INSERT INTO orders
(order_id, customer_id, product_id, order_amount, order_date, order_status)
VALUES
(101, 1, 201, 50000.00, '2026-06-01', 'Delivered'),
(102, 1, 202, 1000.00, '2026-06-02', 'Delivered'),
(103, 2, 203, 2500.00, '2026-06-03', 'Delivered'),
(104, 99, 204, 15000.00, '2026-06-04', 'Delivered'),
(105, 3, 999, 3500.00, '2026-06-05', 'Delivered'),
(106, NULL, 201, 45000.00, '2026-06-06', 'Pending'),
(107, 5, 202, 1200.00, '2026-06-07', 'Cancelled');

-- Inserting samples in the table.(product)
INSERT INTO product(product_id,product_name,category)
VALUES
(201, 'Laptop', 'Electronics'),
(202, 'Mouse', 'Accessories'),
(203, 'Keyboard', 'Accessories'),
(204, 'Monitor', 'Electronics');

-- Inserting samples in the table.(Payment)
INSERT INTO payment
(payment_id, order_id, payment_mode, payment_status, paid_amount, payment_date)
VALUES
(1001, 101, 'eSewa', 'Success', 50000.00, '2026-06-01'),
(1002, 102, 'Card', 'Success', 1000.00, '2026-06-02'),
(1003, 103, 'Khalti', 'Failed', 0.00, '2026-06-03'),
(1004, 105, 'Wallet', 'Success', 3500.00, '2026-06-05'),
(1005, 999, 'Bank Transfer', 'Success', 3000.00, '2026-06-08');


-- checking all the samples from the tables.
Select * from customer;
Select * from orders;
Select * from product;
Select * from payment;

-- now checking the count of the rows in all the tables before the join.


Select count(*) from customer; -- 8
Select count(*) from orders;   -- 7
Select count(*) from product;  -- 4
Select count(*) from payment;  -- 5


-- show the valid orders with the customer details

select o.order_id,
o.customer_id,
c.customer_name,
c.city,
o.order_amount,
o.order_date,
o.order_status from customer as c 
inner join orders as o
on o.customer_id=c.customer_id;


-- show the orders details with the customer name and product name

select o.order_id,
c.customer_name,
c.city,
o.order_amount,
o.order_date,
o.order_status,
p.product_name
from customer as c
inner join orders as o 
on c.customer_id=o.customer_id
inner join product as p
on p.product_id=o.product_id;


-- show the customer_name,customer_details,order_details,payment_mode and product details 
select o.order_id,
c.customer_name,
pro.product_name,
o.order_amount,
o.order_status,
pay.paid_amount,
pay.payment_status

from customer as c
inner join orders as o
on c.customer_id=o.customer_id
inner join product as pro
on o.product_id=pro.product_id 
inner join payment as pay
on o.order_id=pay.order_id;


-- show the previous query but only for kathmandu only.
select o.order_id,
c.customer_name,
pro.product_name,
o.order_amount,
o.order_status,
pay.paid_amount,
pay.payment_status

from customer as c
inner join orders as o
on c.customer_id=o.customer_id
inner join product as pro
on o.product_id=pro.product_id 
inner join payment as pay
on o.order_id=pay.order_id
where c.city='Kathmandu';


-- Aggregation scenario
-- find the total revenue generated by each city

select 
c.city,
sum(pay.paid_amount) as `Total revenue`
from customer as c
inner join orders as o
on c.customer_id=o.customer_id
inner join payment as pay
on o.order_id=pay.order_id
group by c.city;
