-- DATABASE WE ARE USING IN THIS 
USE sql_execution_order;

-- Tables we are using in it.
select * from customers;
select * from orders;


-- BUSINESS SCENARIO

-- FIND THE CITIES WHERE DELIVERED ORDER REVENUE IS MORE THAN 50000
-- SHOW THE CITY AND TOTAL REVENUE, HIGHEST REVENUE FIRST.

select 													-- WORKS AFTER THE HAVING CONDITION. IT WILL PRINT THE VALUES.
c.city,sum(o.order_amount) as `TOTAL REVENUE`
from customers c 										-- CHECKS THE TABLE CUSTOMERS
join orders o 											-- CHECKS THE ORDERS TABLE. BASICALLY JOINS CREATES THE WORKING DATA SETS.
on c.customer_id=o.customer_id							-- CHECKS THE CONDITION WE JUST GAVE.
where o.order_status='Delivered'						-- FILTERS THE ROW LEVEL OF DATA. REMOVES THE UNMATCHING DATA IN THIS .
group by c.city											-- GROUPING THE COLUMNS.
-- having `TOTAL REVENUE ` > 50000 						-- THIS ONLY WORKS IN SQL BUT NOT ON OTHER DATABASES.
having sum(o.order_amount) > 50000						-- PUTS THE CONDITION FILTERING THE GROUPS,AGGREGATED FUNCTION,LIKE SUM,COUNT,AVG ETC
order by `TOTAL REVENUE` desc;							-- ORDER BY RUNS AFTER THE SELECT.


-- KEY TO REMEMBER 

-- WE CANT USE THE ALIAS IN THE WHERE AND HAVING CLAUSE BECAUSE THEY RUN BEFORE THE SELECT CLAUSE SO ONLY THE ORDER BY IS ENABLED TO USE THE ALIAS.


